### ISSUE TITLE
Attribute Release

### ISSUE THREAD

**Issue by slr71** [olabini/clj-cas-client#9]
It appears that the most recent commit to this repository was quite a while ago and I haven't seen any activity on this repository for quite some time. I was going to add support for attribute release. If I get a response on this issue, I'll submit a pull request once I have the changes ready. Otherwise, I'll probably publish my updates to Clojars under a different Group ID.

**Comment by olabini** [comment]
Hi,

I haven't had time for this project for a long time, sadly. If you are ok with forking the project, that has my blessing - I would be fine with putting up a pointer to your project as the new place for updates.

**Comment by slr71** [comment]
That sounds good. I'll let you know when I have something ready and you can add the link then. If you add me to the `clj-cas-client` group on Clojars, I'll be happy to push updated versions to the original group ID. My Clojars ID is `dwr71`.
